// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: IdeaProjects/compielr_project/src/jflex

//package Compiler;
//salam
//section 1


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class lexic {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\0\2\6\1\10"+
    "\3\6\1\11\1\12\1\13\11\14\1\0\1\6\1\4"+
    "\1\15\1\4\2\0\1\16\7\17\1\20\2\17\1\21"+
    "\1\17\1\22\1\17\1\23\1\17\1\24\16\17\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\17\1\36\1\37\1\40\1\41\1\42\1\43\1\17"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\6\1\55\1\6\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\0\1\2\1\0\2\2\2\3"+
    "\24\4\1\0\1\5\1\6\1\0\1\7\1\0\15\4"+
    "\1\2\10\4\1\2\23\4\2\0\2\7\25\4\1\2"+
    "\25\4\1\0\1\7\5\4\1\2\26\4\1\10\11\4"+
    "\1\0\1\4\1\2\11\4\1\2\7\4\1\0\11\4"+
    "\1\0\15\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\56\0\346\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4"+
    "\0\u0422\0\u0450\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564"+
    "\0\56\0\u0114\0\u0592\0\u05c0\0\u0170\0\u05ee\0\u061c\0\u064a"+
    "\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba"+
    "\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a"+
    "\0\u0958\0\u0986\0\u09b4\0\u01cc\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c"+
    "\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc"+
    "\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c"+
    "\0\u0d7a\0\56\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e"+
    "\0\u0ebc\0\u0eea\0\u0f18\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe"+
    "\0\u102c\0\u105a\0\u1088\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e"+
    "\0\u119c\0\u11ca\0\u11f8\0\u1226\0\u1254\0\u1282\0\u12b0\0\u12de"+
    "\0\u130c\0\u133a\0\u1368\0\u1396\0\u13c4\0\u13f2\0\u1420\0\u144e"+
    "\0\u147c\0\u14aa\0\u14d8\0\u1506\0\u1534\0\u1562\0\u1590\0\u0d4c"+
    "\0\u15be\0\u15ec\0\u161a\0\u1648\0\u1676\0\u16a4\0\u16d2\0\u1700"+
    "\0\u172e\0\u175c\0\u178a\0\u17b8\0\u17e6\0\u1814\0\u1842\0\u1870"+
    "\0\u189e\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u1984\0\u19b2\0\u19e0"+
    "\0\u1a0e\0\u1a3c\0\u1a6a\0\u1a98\0\u01cc\0\u1ac6\0\u1af4\0\u1b22"+
    "\0\u1b50\0\u1b7e\0\u1bac\0\u1bda\0\u1c08\0\u1c36\0\u1c64\0\u1c92"+
    "\0\u1cc0\0\u1cee\0\u1d1c\0\u1d4a\0\u1d78\0\u1da6\0\u1dd4\0\u1e02"+
    "\0\u1e30\0\u1e5e\0\u144e\0\u1e8c\0\u1eba\0\u1ee8\0\u1f16\0\u1f44"+
    "\0\u1f72\0\u1fa0\0\u1fce\0\u1ffc\0\u202a\0\u2058\0\u2086\0\u20b4"+
    "\0\u20e2\0\u2110\0\u213e\0\u216c\0\u219a\0\u21c8\0\u21f6\0\u2224"+
    "\0\u2252\0\u2280\0\u22ae\0\u22dc\0\u230a\0\u2338\0\u2366\0\u2394"+
    "\0\u23c2\0\u23f0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\3\1\4\1\5\1\6\1\7\1\6"+
    "\1\10\1\11\1\12\1\13\1\4\4\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\14\1\27\1\14\1\30\1\14\1\31\1\14\1\32"+
    "\1\33\1\34\1\35\1\14\1\36\1\37\3\14\1\40"+
    "\60\0\1\2\70\0\1\6\40\0\2\5\2\0\1\5"+
    "\1\41\50\5\7\0\1\6\61\0\2\42\51\0\1\43"+
    "\1\0\1\44\54\0\1\42\1\0\2\45\52\0\1\42"+
    "\1\0\2\13\54\0\2\14\1\0\37\14\14\0\2\14"+
    "\1\0\13\14\1\46\23\14\14\0\2\14\1\0\26\14"+
    "\1\47\10\14\14\0\2\14\1\0\13\14\1\50\23\14"+
    "\14\0\2\14\1\0\10\14\1\51\16\14\1\52\7\14"+
    "\14\0\2\14\1\0\24\14\1\53\1\14\1\54\6\14"+
    "\1\55\1\14\14\0\2\14\1\0\7\14\1\56\6\14"+
    "\1\57\2\14\1\60\2\14\1\61\12\14\14\0\2\14"+
    "\1\0\13\14\1\62\10\14\1\63\12\14\14\0\2\14"+
    "\1\0\21\14\1\64\1\14\1\65\10\14\1\66\2\14"+
    "\14\0\2\14\1\0\7\14\1\67\7\14\1\70\1\14"+
    "\1\71\2\14\1\72\12\14\14\0\2\14\1\0\24\14"+
    "\1\73\12\14\14\0\2\14\1\0\14\14\1\74\5\14"+
    "\1\75\1\76\13\14\14\0\2\14\1\0\24\14\1\77"+
    "\12\14\14\0\2\14\1\0\7\14\1\100\3\14\1\101"+
    "\15\14\1\102\5\14\14\0\2\14\1\0\7\14\1\103"+
    "\16\14\1\104\2\14\1\105\5\14\14\0\2\14\1\0"+
    "\13\14\1\106\23\14\14\0\2\14\1\0\16\14\1\107"+
    "\11\14\1\110\1\111\1\14\1\112\1\14\1\113\1\14"+
    "\14\0\2\14\1\0\16\14\1\114\7\14\1\115\10\14"+
    "\14\0\2\14\1\0\24\14\1\116\12\14\14\0\2\14"+
    "\1\0\16\14\1\117\20\14\56\0\1\6\10\120\1\121"+
    "\45\120\2\44\1\122\1\123\52\44\13\0\2\14\1\0"+
    "\33\14\1\124\3\14\14\0\2\14\1\0\17\14\1\125"+
    "\17\14\14\0\2\14\1\0\7\14\1\126\27\14\14\0"+
    "\2\14\1\0\27\14\1\127\7\14\14\0\2\14\1\0"+
    "\27\14\1\130\7\14\14\0\2\14\1\0\24\14\1\131"+
    "\12\14\14\0\2\14\1\0\13\14\1\132\23\14\14\0"+
    "\2\14\1\0\30\14\1\133\6\14\14\0\2\14\1\0"+
    "\27\14\1\133\1\134\6\14\14\0\2\14\1\0\7\14"+
    "\1\72\27\14\14\0\2\14\1\0\7\14\1\135\27\14"+
    "\14\0\2\14\1\0\23\14\1\136\13\14\14\0\2\14"+
    "\1\0\14\14\1\137\22\14\14\0\2\14\1\0\31\14"+
    "\1\140\5\14\14\0\2\14\1\0\27\14\1\133\7\14"+
    "\14\0\2\14\1\0\31\14\1\141\5\14\14\0\2\14"+
    "\1\0\30\14\1\142\6\14\14\0\2\14\1\0\21\14"+
    "\1\143\15\14\14\0\2\14\1\0\23\14\1\144\13\14"+
    "\14\0\2\14\1\0\24\14\1\145\12\14\14\0\2\14"+
    "\1\0\26\14\1\74\10\14\14\0\2\14\1\0\30\14"+
    "\1\146\6\14\14\0\2\14\1\0\25\14\1\147\11\14"+
    "\14\0\2\14\1\0\27\14\1\150\1\151\6\14\14\0"+
    "\2\14\1\0\23\14\1\152\13\14\14\0\2\14\1\0"+
    "\30\14\1\153\6\14\14\0\2\14\1\0\33\14\1\74"+
    "\3\14\14\0\2\14\1\0\21\14\1\154\15\14\14\0"+
    "\2\14\1\0\11\14\1\155\25\14\14\0\2\14\1\0"+
    "\17\14\1\156\4\14\1\157\12\14\14\0\2\14\1\0"+
    "\10\14\1\160\26\14\14\0\2\14\1\0\30\14\1\161"+
    "\6\14\14\0\2\14\1\0\24\14\1\162\12\14\14\0"+
    "\2\14\1\0\7\14\1\163\16\14\1\164\10\14\14\0"+
    "\2\14\1\0\25\14\1\165\11\14\14\0\2\14\1\0"+
    "\17\14\1\166\17\14\14\0\2\14\1\0\23\14\1\167"+
    "\13\14\14\0\2\14\1\0\17\14\1\170\6\14\1\171"+
    "\10\14\14\0\2\14\1\0\7\14\1\172\21\14\1\173"+
    "\3\14\1\74\1\14\14\0\2\14\1\0\17\14\1\174"+
    "\1\14\1\175\15\14\14\0\2\14\1\0\17\14\1\176"+
    "\17\14\1\0\10\120\1\177\55\120\1\177\1\120\1\200"+
    "\43\120\2\0\1\122\66\0\2\14\1\0\1\201\36\14"+
    "\14\0\2\14\1\0\23\14\1\202\13\14\14\0\2\14"+
    "\1\0\12\14\1\203\24\14\14\0\2\14\1\0\30\14"+
    "\1\204\6\14\14\0\2\14\1\0\13\14\1\205\23\14"+
    "\14\0\2\14\1\0\21\14\1\206\15\14\14\0\2\14"+
    "\1\0\7\14\1\207\27\14\14\0\2\14\1\0\13\14"+
    "\1\74\23\14\14\0\2\14\1\0\11\14\1\210\25\14"+
    "\14\0\2\14\1\0\27\14\1\170\7\14\14\0\2\14"+
    "\1\0\27\14\1\211\1\212\6\14\14\0\2\14\1\0"+
    "\7\14\1\213\27\14\14\0\2\14\1\0\10\14\1\176"+
    "\26\14\14\0\2\14\1\0\22\14\1\214\14\14\14\0"+
    "\2\14\1\0\13\14\1\215\23\14\14\0\2\14\1\0"+
    "\27\14\1\173\7\14\14\0\2\14\1\0\7\14\1\216"+
    "\27\14\14\0\2\14\1\0\7\14\1\202\27\14\14\0"+
    "\2\14\1\0\24\14\1\217\12\14\14\0\2\14\1\0"+
    "\21\14\1\220\2\14\1\162\12\14\14\0\2\14\1\0"+
    "\30\14\1\221\6\14\14\0\2\14\1\0\13\14\1\222"+
    "\23\14\14\0\2\14\1\0\15\14\1\74\21\14\14\0"+
    "\2\14\1\0\17\14\1\223\17\14\14\0\2\14\1\0"+
    "\21\14\1\74\15\14\14\0\2\14\1\0\20\14\1\224"+
    "\16\14\14\0\2\14\1\0\32\14\1\225\4\14\14\0"+
    "\2\14\1\0\30\14\1\226\6\14\14\0\2\14\1\0"+
    "\21\14\1\227\15\14\14\0\2\14\1\0\31\14\1\230"+
    "\5\14\14\0\2\14\1\0\26\14\1\202\10\14\14\0"+
    "\2\14\1\0\30\14\1\227\6\14\14\0\2\14\1\0"+
    "\17\14\1\231\17\14\14\0\2\14\1\0\13\14\1\72"+
    "\23\14\14\0\2\14\1\0\30\14\1\134\6\14\14\0"+
    "\2\14\1\0\11\14\1\232\25\14\14\0\2\14\1\0"+
    "\27\14\1\74\7\14\14\0\2\14\1\0\24\14\1\233"+
    "\12\14\14\0\2\14\1\0\23\14\1\234\13\14\14\0"+
    "\2\14\1\0\13\14\1\235\23\14\14\0\2\14\1\0"+
    "\12\14\1\74\24\14\14\0\2\14\1\0\7\14\1\236"+
    "\27\14\14\0\2\14\1\0\21\14\1\133\15\14\1\0"+
    "\10\120\1\177\1\120\1\122\43\120\13\0\2\14\1\0"+
    "\26\14\1\237\10\14\14\0\2\14\1\0\30\14\1\74"+
    "\6\14\14\0\2\14\1\0\2\14\1\240\1\241\33\14"+
    "\14\0\2\14\1\0\26\14\1\242\10\14\14\0\2\14"+
    "\1\0\26\14\1\243\10\14\14\0\2\14\1\0\13\14"+
    "\1\244\23\14\14\0\2\14\1\0\20\14\1\74\16\14"+
    "\14\0\2\14\1\0\16\14\1\74\20\14\14\0\2\14"+
    "\1\0\30\14\1\217\6\14\14\0\2\14\1\0\17\14"+
    "\1\245\17\14\14\0\2\14\1\0\31\14\1\246\5\14"+
    "\11\0\1\247\2\0\2\14\1\0\37\14\14\0\2\14"+
    "\1\0\23\14\1\250\13\14\14\0\2\14\1\0\21\14"+
    "\1\251\15\14\11\0\1\6\2\0\2\14\1\0\37\14"+
    "\14\0\2\14\1\0\13\14\1\252\23\14\14\0\2\14"+
    "\1\0\7\14\1\253\27\14\14\0\2\14\1\0\26\14"+
    "\1\254\10\14\14\0\2\14\1\0\32\14\1\133\4\14"+
    "\14\0\2\14\1\0\7\14\1\255\27\14\14\0\2\14"+
    "\1\0\7\14\1\55\27\14\14\0\2\14\1\0\13\14"+
    "\1\256\23\14\14\0\2\14\1\0\17\14\1\257\17\14"+
    "\14\0\2\14\1\0\26\14\1\260\10\14\14\0\2\14"+
    "\1\0\11\14\1\261\11\14\1\152\13\14\14\0\2\14"+
    "\1\0\16\14\1\262\20\14\14\0\2\14\1\0\33\14"+
    "\1\263\3\14\14\0\2\14\1\0\27\14\1\264\7\14"+
    "\14\0\2\14\1\0\30\14\1\117\6\14\14\0\2\14"+
    "\1\0\26\14\1\265\10\14\14\0\2\14\1\0\23\14"+
    "\1\266\13\14\14\0\2\14\1\0\17\14\1\267\17\14"+
    "\14\0\2\14\1\0\7\14\1\270\27\14\14\0\2\14"+
    "\1\0\30\14\1\271\6\14\14\0\2\14\1\0\7\14"+
    "\1\260\27\14\14\0\2\14\1\0\23\14\1\272\13\14"+
    "\14\0\2\14\1\0\21\14\1\202\15\14\11\0\1\273"+
    "\60\0\2\14\1\0\12\14\1\170\24\14\14\0\2\14"+
    "\1\0\21\14\1\274\15\14\14\0\2\14\1\0\22\14"+
    "\1\275\14\14\14\0\2\14\1\0\23\14\1\276\13\14"+
    "\14\0\2\14\1\0\14\14\1\277\22\14\14\0\2\14"+
    "\1\0\15\14\1\133\21\14\14\0\2\14\1\0\11\14"+
    "\1\300\25\14\14\0\2\14\1\0\11\14\1\74\25\14"+
    "\14\0\2\14\1\0\23\14\1\74\13\14\14\0\2\14"+
    "\1\0\30\14\1\301\6\14\14\0\2\14\1\0\26\14"+
    "\1\302\10\14\14\0\2\14\1\0\17\14\1\303\17\14"+
    "\14\0\2\14\1\0\7\14\1\274\27\14\14\0\2\14"+
    "\1\0\30\14\1\304\6\14\14\0\2\14\1\0\23\14"+
    "\1\133\13\14\14\0\2\14\1\0\11\14\1\202\25\14"+
    "\11\0\1\273\2\0\2\14\1\0\37\14\14\0\2\14"+
    "\1\0\31\14\1\133\5\14\11\0\1\305\60\0\2\14"+
    "\1\0\35\14\1\74\1\14\14\0\2\14\1\0\13\14"+
    "\1\306\23\14\14\0\2\14\1\0\11\14\1\307\25\14"+
    "\14\0\2\14\1\0\7\14\1\310\27\14\14\0\2\14"+
    "\1\0\30\14\1\311\6\14\14\0\2\14\1\0\14\14"+
    "\1\312\22\14\14\0\2\14\1\0\24\14\1\313\12\14"+
    "\14\0\2\14\1\0\13\14\1\125\23\14\14\0\2\14"+
    "\1\0\13\14\1\314\23\14\11\0\1\6\60\0\2\14"+
    "\1\0\23\14\1\315\13\14\14\0\2\14\1\0\13\14"+
    "\1\316\23\14\14\0\2\14\1\0\11\14\1\133\25\14"+
    "\14\0\2\14\1\0\13\14\1\174\23\14\14\0\2\14"+
    "\1\0\25\14\1\317\11\14\14\0\2\14\1\0\23\14"+
    "\1\320\13\14\14\0\2\14\1\0\15\14\1\165\21\14"+
    "\14\0\2\14\1\0\30\14\1\170\6\14\14\0\2\14"+
    "\1\0\24\14\1\321\12\14\11\0\1\305\2\0\2\14"+
    "\1\0\37\14\14\0\2\14\1\0\17\14\1\322\17\14"+
    "\14\0\2\14\1\0\14\14\1\74\22\14\14\0\2\14"+
    "\1\0\36\14\1\311\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9246];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\0\1\11\1\0\30\1\1\0"+
    "\1\11\1\1\1\0\1\1\1\0\52\1\2\0\1\11"+
    "\54\1\1\0\47\1\1\0\23\1\1\0\11\1\1\0"+
    "\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public lexic(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public String yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* white space */
            }
            // fall through
          case 9: break;
          case 2:
            { return yytext();
            }
            // fall through
          case 10: break;
          case 3:
            { return ("T_INTLITERAL" + " " + yytext());
            }
            // fall through
          case 11: break;
          case 4:
            { return ("T_ID"+ " " + yytext());
            }
            // fall through
          case 12: break;
          case 5:
            { return ("T_STRINGLITERAL" + " " + yytext());
            }
            // fall through
          case 13: break;
          case 6:
            { return ("T_DOUBLELITERAL" + " " + yytext());
            }
            // fall through
          case 14: break;
          case 7:
            { /* comment */
            }
            // fall through
          case 15: break;
          case 8:
            { return ("T_BOOLEANLITERAL" + " " + yytext());
            }
            // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
